name: tonic
version: 0.2.3

description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
authors:
- Oliver Steele <steele@osteele.com>
- Rody Davis <rody.davis.jr@gmail.com>
homepage: http://github.com/osteele/dart-tonic
documentation:

environment:
  # might work with earlier versions of 2.0.0, but hasn't been tested
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  # might work with collection: ^1.0.0, but hasn't been tested
  collection: ^1.14.0

dev_dependencies:
  # might work with test: ^1.0.0, but hasn't been tested
  test: ^1.3.0
