name: tonic
version: 0.2.4

description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
homepage: https://github.com/osteele/dart-tonic
repository: https://github.com/osteele/dart-tonic
documentation: https://pub.dev/documentation/tonic/latest/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.8
